spring.application.name=taskservice

server.address=127.0.0.1
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/taskservice_db
spring.datasource.username=admin
spring.datasource.password=f6T2g9Vb
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG